import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import React from "react";

import { useBgLightblue } from "@/hooks/useBgLightblue";
import { useCounter } from "@/hooks/useCounter";
import { useInputArray } from "@/hooks/useInputArray";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [count, isShow, handleClick, handleDisplay] = useCounter();
  const [text, array, handleChange, handleAdd] = useInputArray();
  useBgLightblue();

  return (
    <html lang="ja">
      <body>
        {React.cloneElement(children as React.ReactElement, {
          count,
          isShow,
          handleClick,
          handleDisplay,
          text,
          array,
          handleChange,
          handleAdd,
        })}
      </body>
    </html>
  );
}
